version: '3'
services:
  mysite:
    build:
      context: ./
      dockerfile: Dockerfile
    image: blog_app
    ports:
      - "8000:8000"
    command:
      - "runserver"
      - "0.0.0.0:8000"